### ISSUE TITLE
Running the action only deletes one asset at the time

### ISSUE THREAD

**Issue by axelferdinand** [swiftmade/statamic-clear-assets#10] opened 2023-03-06 13:55 UTC
When I run the command, I get this error:

```
Found 1398 unused assets, taking up 564.86 MB of storage.

 What would you like to do? [Delete all]:
  [0] Delete all
  [1] Choose what to delete
  [2] Don't do anything
 > 0

Removing img/2022/april/andre/arctic-haute-route-ski-and-sail-northern-norway-norwegian-adventure-company.jpg

   ErrorException 

  foreach() argument must be of type array|object, string given

  at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:113
    109▕     public static function dot($array, $prepend = '')
    110▕     {
    111▕         $results = [];
    112▕ 
  ➜ 113▕         foreach ($array as $key => $value) {
    114▕             if (is_array($value) && ! empty($value)) {
    115▕                 $results = array_merge($results, static::dot($value, $prepend.$key.'.'));
    116▕             } else {
    117▕                 $results[$prepend.$key] = $value;

      +8 vendor frames 
  9   [internal]:0
      Statamic\Listeners\UpdateAssetReferences::Statamic\Listeners\{closure}(Object(Statamic\Entries\Entry))

      +47 vendor frames 
  57  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Running on v3.4.5

**Comment by aozisik** [comment] 2023-03-10 12:14
Hi @axelferdinand,

Someone else reported the same issue before, but so far I couldn't reproduce it.
There's a workaround that helps, so you might want to try this:

https://github.com/swiftmade/statamic-clear-assets/issues/5#issuecomment-1239392898

Closing this, but feel free to reopen if your issue is not fixed.

**Closed as completed by aozisik** 2023-03-10 12:14 UTC

**Comment by axelferdinand** [comment] 2023-03-10 12:17
Thank you, will try this!
