### ISSUE TITLE
Throwing error after 'delete all'

### ISSUE THREAD

**Issue by ewhicher** [swiftmade/statamic-clear-assets#5] opened 2022-09-07 09:16 UTC
I'm getting the following error in the console after I choose option [0] - delete all.

```
   ErrorException 

  foreach() argument must be of type array|object, string given

  at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:114
    110▕     public static function dot($array, $prepend = '')
    111▕     {
    112▕         $results = [];
    113▕ 
  ➜ 114▕         foreach ($array as $key => $value) {
    115▕             if (is_array($value) && ! empty($value)) {
    116▕                 $results = array_merge($results, static::dot($value, $prepend.$key.'.'));
    117▕             } else {
    118▕                 $results[$prepend.$key] = $value;

      +8 vendor frames 
  9   [internal]:0
      Statamic\Listeners\UpdateAssetReferences::Statamic\Listeners\{closure}(Object(Statamic\Entries\Entry))

      +48 vendor frames 
  58  please:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Here is my `php please support:details`:

```
Environment
Application Name: Statamic
Laravel Version: 9.28.0
PHP Version: 8.1.4
Composer Version: 2.2.9
Environment: local
Debug Mode: ENABLED
URL: bon.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: regex
Version: 3.3.34 PRO

Statamic Addons
aryehraber/statamic-color-extractor: 1.3.0
statamic/migrator: dev-master
swiftmade/statamic-clear-assets: 1.1.0
visuellverstehen/statamic-classify: 2.4.0
```

**Comment by aozisik** [comment] 2022-09-07 09:17
Thanks for the report @ewhicher. I'll try to take a look at this later today.

**Comment by ewhicher** [comment] 2022-09-07 09:20
Thanks for the quick reply!
I posted before I had finished writing the issue, see updated above with some env details :)

**Comment by aozisik** [comment] 2022-09-07 13:29
@ewhicher  This is strange. I can't reproduce this with the same versions / plugins, etc.
Just as an experiment, does setting `update_references` to false in `config/statamic/system.php` help?

**Comment by ewhicher** [comment] 2022-09-07 13:40
@aozisik this did the trick! Will this mean I need to do anything manually now too?

Thanks so much - you just saved me from removing over 1000 images manually 😅

**Comment by aozisik** [comment] 2022-09-07 14:36
@ewhicher  I'm happy it worked! 

It's safe to assume since you're only deleting unused assets, those triggered events shouldn't matter. It would probably make sense to revert that value back to true once you're done :)

Out of curiosity, do you have the full stack trace of the error you encountered? Could still be helpful to see if there's something I'm missing. (Maybe in your laravel.log file).

**Comment by aozisik** [comment] 2022-09-08 08:14
Closing this now, but feel free to email me that full stack trace you got at hello@swiftmade.co if you happen to find it :) Cheers!

**Closed as completed by aozisik** 2022-09-08 08:14 UTC

**Comment by johncarter-** [comment] 2023-02-01 17:47
Just had this happen to me, config key did the trick too. Here's the stacktrace:

```
[2023-02-01 17:33:41] local.ERROR: Array to string conversion {"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php:170)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(170): preg_replace_callback()
#3 /var/www/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(105): Statamic\\Assets\\AssetReferenceUpdater->updateStatamicUrlsInStringValue()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Statamic\\Assets\\AssetReferenceUpdater->Statamic\\Assets\\{closure}()
#5 /var/www/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(107): Illuminate\\Support\\Collection->each()
#6 /var/www/html/vendor/statamic/cms/src/Assets/AssetReferenceUpdater.php(40): Statamic\\Assets\\AssetReferenceUpdater->updateBardFieldValues()
#7 /var/www/html/vendor/statamic/cms/src/Data/DataReferenceUpdater.php(63): Statamic\\Assets\\AssetReferenceUpdater->recursivelyUpdateFields()
#8 /var/www/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(99): Statamic\\Data\\DataReferenceUpdater->updateReferences()
#9 [internal function]: Statamic\\Listeners\\UpdateAssetReferences->Statamic\\Listeners\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(739): Illuminate\\Support\\Arr::map()
#12 /var/www/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(100): Illuminate\\Support\\Collection->map()
#13 /var/www/html/vendor/statamic/cms/src/Listeners/UpdateAssetReferences.php(76): Statamic\\Listeners\\UpdateAssetReferences->replaceReferences()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(107): Statamic\\Listeners\\UpdateAssetReferences->handleDeleted()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Events\\CallQueuedListener->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\\Container\\BoundMethod::call()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\\Queue\\Jobs\\Job->fire()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(57): Illuminate\\Queue\\SyncQueue->push()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(591): Illuminate\\Queue\\Queue->pushOn()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(515): Illuminate\\Events\\Dispatcher->queueHandler()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(451): Illuminate\\Events\\Dispatcher->dispatch()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Events/Dispatchable.php(14): event()
#38 /var/www/html/vendor/statamic/cms/src/Assets/Asset.php(609): Statamic\\Events\\Event::dispatch()
#39 /var/www/html/vendor/swiftmade/statamic-clear-assets/src/ClearAssets.php(99): Statamic\\Assets\\Asset->delete()
#40 /var/www/html/vendor/swiftmade/statamic-clear-assets/src/ClearAssets.php(55): Swiftmade\\StatamicClearAssets\\ClearAssets->removeAsset()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Swiftmade\\StatamicClearAssets\\ClearAssets->Swiftmade\\StatamicClearAssets\\{closure}()
#42 /var/www/html/vendor/swiftmade/statamic-clear-assets/src/ClearAssets.php(55): Illuminate\\Support\\Collection->each()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Conditionable/Traits/Conditionable.php(34): Swiftmade\\StatamicClearAssets\\ClearAssets->Swiftmade\\StatamicClearAssets\\{closure}()
#44 /var/www/html/vendor/swiftmade/statamic-clear-assets/src/ClearAssets.php(56): Illuminate\\Support\\Collection->when()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Swiftmade\\StatamicClearAssets\\ClearAssets->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(663): Illuminate\\Container\\BoundMethod::call()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call()
#51 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#53 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#54 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#55 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#58 /var/www/html/please(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#59 {main}
"} 
```

**Comment by sjclark** [comment] 2023-08-27 04:44
Just advising this happened to me to - the workaround also worked.
